### PR TITLE
0.16.0

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by bartlomieju** [comment]
Required for https://github.com/denoland/deno/pull/13563

**Comment by bartlomieju** [comment]
Waiting for new `deno_ast` release

**Comment by littledivy** [comment]
> Waiting for new `deno_ast` release

Locked `deno_ast` to 0.11.0 (Same as CLI) for now.

**Review by littledivy — APPROVED** [review]
LGTM

**Review by lucacasonato — APPROVED** [review]

**Pull request merged**
