### PR TITLE
feat: support external specifiers

### PR DESCRIPTION
**Pull request by littledivy**

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
LGTM

**Review by lucacasonato — CHANGES_REQUESTED** [review]
Actually missing tests.

**Comment by littledivy** [comment]
@lucacasonato https://github.com/denoland/eszip/pull/54/files#diff-3e1e5ff1aa907e0d31ff2aa9a543dab79c7a08e778cca3cff47ec86e275bd28eR13 There is a test in `lib/eszip_test.ts`

**Review by lucacasonato — COMMENTED** [review]
@littledivy I meant a Rust side tests that also checks that the "external" specifier is not actually included in the eszip. I.e you build, and then you parse and check that only the things you expect are in the eszip. The building can happen beforehand. Take a look at `file_format_parse_redirect` for example.

**Comment by littledivy** [comment]
Added

**Review by lucacasonato — APPROVED** [review]
LGTM

**Pull request merged**
